### PR TITLE
add HPO msg consumer

### PR DESCRIPTION
**Pull request by mightqxc**
Not sure if I understand correctly...

- '''_Basically startEvent = endEvent = the "id_"''' (from mail) - Does it mean to insert only one event for each HPO message? Then what about ["_nEvents = # of HP samples to be evaluated_"](https://docs.google.com/presentation/d/1O1b7M_w9qpB6YJydIsJdYNnRNHESUAJHARDlMGppQyI/edit#slide=id.g7fdab89324_0_11)?
- Need other change in the db proxy method?
- Is it correct to ignore parameter and loss from the message [here](https://github.com/PanDAWMS/panda-jedi/compare/flin?expand=1#diff-c1c8af32091bda17b417c18ca5893a2bR47)? Nowhere in the event table to put them into.
- ["_The task is finished when iDDS sends a message_"](https://docs.google.com/presentation/d/1O1b7M_w9qpB6YJydIsJdYNnRNHESUAJHARDlMGppQyI/edit#slide=id.g7fdab89324_0_11) - Who to receive this message and made the task finished? Do we need another functionality in JEDI message consumer?
- This code may not work, depending on how the message broker of iDDS will be set. If iDDS sends both tape carousel and HPO messages to the same message queue, then both JEDI plugin need to be changed. Otherwise, (separate message queues, which I prefer) it's fine.

### CODE REVIEW

**Comment by tmaeno** [comment]
Each message can contain multiple IDs. You could change tbIF.insertHpoEventAboutIdds_JEDI() to take a list of IDs instead of startEvent and endEvent.

nEvents is dynamically counted by JobGenerator so that the msg consumer doesn't have to set in the database. Actually HP samples don't have a corresponding dataset (record) in this model. 

> Is it correct to ignore parameter and loss from the message here? 

Correct.

> finish

There is API to finish a task.

https://github.com/PanDAWMS/panda-server/blob/master/pandaserver/userinterface/UserIF.py#L726-L728

It would be good to add this function to the consumer too.

**Comment by mightqxc** [comment]
Thanks.

> It would be good to add this function to the consumer too.
When should it call finishTask? Is there another kind of message from iDDS to signal finish?

**Comment by tmaeno** [comment]
> Is there another kind of message (different than insert-events message) from iDDS to signal finish?

Yes.

**Comment by mightqxc** [comment]
@tmaeno 
All required functions are included. Any other comments appreciated.

I haven't test yet, maybe next week.

BTW, I found that I already have protection so that consumer plugins can still work even if different messages in the same message queue. When they get wrong messages, they will just dump lots of error messages, and call NACK (so message will stay in queue for other consumer processes), and keep working.

**Comment by mightqxc** [comment]
I think this can be merged

**Pull request merged**
