### PR TITLE
analy broker: exclude site where user queues long

### PR DESCRIPTION
**Pull request by mightqxc**

### CODE REVIEW

**Comment by mightqxc** [comment]
Will move parameters to gdpconfig after algorithm is agreed

**Comment by mightqxc** [comment]
An example about a filterer site:

```
2020-07-13 11:46:50,740 panda.log.AtlasAnalJobBroker: INFO     <jediTaskID=21872710>   skip site=WEIZMANN/SCORE nQueue_pq_user(25)>limit(11.15)=base queue ratio on PQ (0.050) * nRunning_pq_total (223) and criteria=-user_queue_length
```

**Comment by tmaeno** [comment]
One problem is that getUsersJobsStats_JEDI counts all user jobs, so that if a user has too many jobs at PQ_1 other users cannot send jobs to PQ_1. Jobs should be counted per user so that each user is throttled independently. Also, it would be problematic if getUsersJobsStats_JEDI always hits jobsActive4. Might be better to use a summary table. Another problem is the filter is evaluated in the look starting with

https://github.com/PanDAWMS/panda-jedi/blob/master/pandajedi/jedibrokerage/AtlasAnalJobBroker.py#L156

so that it will trigger data transfers when PQs are skipped due to the filter, which is not good at least for now.
One possibility is to add over-queueing PQs to problematic_sites_dict and remove them at

https://github.com/PanDAWMS/panda-jedi/blob/master/pandajedi/jedibrokerage/AtlasAnalJobBroker.py#L1235

**Comment by mightqxc** [comment]
> One problem is that getUsersJobsStats_JEDI counts all user jobs, so that if a user has too many jobs at PQ_1 other users cannot send jobs to PQ_1. Jobs should be counted per user so that each user is throttled independently. 

I think getUsersJobsStats_JEDI counts jobs per user, with group by produsername:
```
"GROUP BY prodUserName,jobStatus,gshare,computingSite "
```

> Also, it would be problematic if getUsersJobsStats_JEDI always hits jobsActive4. Might be better to use a summary table. 

Which is the summary table we have? Seems JOBS_SHARE_STATS does not have column for user information.


>Another problem is the filter is evaluated in the look starting with
> 
> https://github.com/PanDAWMS/panda-jedi/blob/master/pandajedi/jedibrokerage/AtlasAnalJobBroker.py#L156
> 
> so that it will trigger data transfers when PQs are skipped due to the filter, which is not good at least for now.
> One possibility is to add over-queueing PQs to problematic_sites_dict and remove them at
> 
> https://github.com/PanDAWMS/panda-jedi/blob/master/pandajedi/jedibrokerage/AtlasAnalJobBroker.py#L1235

Fixed to use problematic_sites_dict.

**Comment by tmaeno** [comment]
OK, I didn't realize that you used user_name in the brokerage, but then each getUsersJobsStats_JEDI always scans all user jobs in jobsActive4. If existing summary tables don't have proper columns, would be good to make a new table.

**Comment by mightqxc** [comment]
Can I use the existing cache table in PanDA DB? In this case the real scan in jobsActive4 only runs at lower frequency, say every 5 minutes (with small cost of using non-real-time stats).

I try to avoid adding new tables in general.

Adding @fbarreir as talking about PanDA DB.

**Comment by fbarreir** [comment]
What is going to generate the summary?
I would use the cache table if you want to have ONE json containing all users. With the current oracle version you can't query inside the json file and have to extract the whole thing. 
If you prefer to query user by user, it would probably be less messy to make a new table.

**Comment by mightqxc** [comment]
Both ways look doable to me; I can either query for one json blob for all users, or query one user at a time.

@tmaeno @fbarreir Do you have any other concern between these two ways? (about DB loading? logic of the algorithm?)

If we are indifferent to these ways, I will try the cache table first, which requires less implementation doesn't need new table.

**Comment by tmaeno** [comment]
That would depend on the size of the json data and read frequency. Can you estimate them?

**Comment by mightqxc** [comment]
The json (all users x all queues) is about 128k

**Comment by tmaeno** [comment]
So I suppose that JEDI processes ~60 analysis tasks per min and 128kBps of reading rate would be acceptable. 

One thing. Probably the refresh interval of 5 min is too long. The summary table for production brokerage is refreshed every minute, but it sometimes causes too many assigned jobs especially at small PQs due to non-real-time data when many processes/threads are concurrently running for the same gshare. 

BTW, before deploying this change to production JEDI, better to be reported in WFMS since this will increase the number of pending tasks and users will be upset if the change is added before they knew that.

**Comment by mightqxc** [comment]
> So I suppose that JEDI processes ~60 analysis tasks per min and 128kBps of reading rate would be acceptable.

I think the actual read rate from DB can be lower, since the data can be cached in memory on each nodes (and there will be timestamp to indicate the expiry of cached data).

> One thing. Probably the refresh interval of 5 min is too long. The summary table for production brokerage is refreshed every minute, but it sometimes causes too many assigned jobs especially at small PQs due to non-real-time data when many processes/threads are concurrently running for the same gshare.

OK, I will try 1-min interval.

> BTW, before deploying this change to production JEDI, better to be reported in WFMS since this will increase the number of pending tasks and users will be upset if the change is added before they knew that.

In the first deployment I plan to make it dry-run (not really removing PQs) to test the mechanism.
When ready, we report to WFMS and deploy the real stuff.

**Comment by mightqxc** [comment]
The cache mechanism is implemented and working; testing on atlas-jedi-00.

Besides, here is an example showing this filter can stop thousands of queuing jobs:
```
2020-07-14 14:10:38,629 panda.log.AtlasAnalJobBroker: INFO     <jediTaskID=21881723>  consider BNL as bad site for the user due to long queue of the user: nQueue_pq_user(8560) > limit(840.000) = static max nQ/nR (2.000) * nRunning_pq_user (420) 
2020-07-14 14:10:38,629 panda.log.AtlasAnalJobBroker: INFO     <jediTaskID=21881723>  consider SLAC as bad site for the user due to long queue of the user: nQueue_pq_user(204) > limit(36.000) = static max nQ/nR (2.000) * nRunning_pq_user (18)
```

@tmaeno  Can I add the related parameter as following to the gdpconfig table?

```
                base_default_queue_length_per_pq_user = 5
                base_queue_ratio_on_pq = 0.05
                static_max_queue_running_ratio = 2.0
                max_expected_wait_hour = 12
```

**Comment by tmaeno** [comment]
OK.

**Comment by mightqxc** [comment]
Done. Ready to merge (now still dry-run)

**Comment by tmaeno** [comment]
Looks good.

**Pull request merged**
