### PR TITLE
queue filler: real run

### PR DESCRIPTION
**Pull request by mightqxc**

### CODE REVIEW

**Comment by mightqxc** [comment]
Hi @tmaeno 

I found some preassigned tasks got pending soon during brokerage, e.g. 

```
2021-04-12 10:51:40,893 panda.log.AtlasQueueFillerWatchDog: DEBUG    do_preassign #ATM #KV jediTaskID=24804088 action=do_preassign site=IN2P3-CPPM rtype=
MCORE preassigned
2021-04-12 11:11:46,249 panda.log.AtlasQueueFillerWatchDog: DEBUG    undo_preassign #ATM #KV jediTaskID=24804088 action=undo_preassign site=IN2P3-CPPM rtype=MCORE un-preassinged since task paused or terminated

2021-04-12 11:04:34.880321 :   skip site=IN2P3-CPPM/MCORE weight=0.14285714285714285 due to nDefined+nActivated+nStarting=25 (nAssigned ignored due to data locally available) greater than max(20,2*nRun) nRun=0 nAct=0 nStart=25 nDef=0 nPilot=0 totalSizeMB=13351 totalNumFiles=39 fileSizeToMoveMB=0 nFilesToMove=0 t1W=1 weightNw=2.5 ( closeness=0 nFilesQueued=0 throughputMBps=None Network weight:True ) criteria=-cap
```

I suppose this was because the brokerage only looked at MCORE and thought it had enough queuing jobs, while the queue filler saw the whole site and thought the site need more jobs. Here the SCORE part of the site indeed had no job at that time:

```
2021-04-12 11:01:53,101    site=IN2P3-CPPM/SCORE ... nRun=0 nAct=0 nAss=0 nStart=0 nDef=0 manyAss=1.0
```

So the algorithms of brokerage and queue filler do not always agree with each other.

Do you think it a serious issue (that makes tasks get pending) to fix? Or somewhat tolerable?
Thanks.

**Comment by tmaeno** [comment]
Is it correct that

1. 24804088 was assigned at 2021-04-12 10:51:40,893 since IN2P3-CPPM was empty,
2. some jobs were assigned to IN2P3-CPPM/MCORE until 2021-04-12 11:04:34.880321, and 
3. the brokerage set 24804088 pending since there were enough jobs at IN2P3-CPPM/MCORE

?

Then did the queue filler release all IN2P3-CPPM tasks since IN2P3-CPPM had enough jobs?

**Comment by mightqxc** [comment]
I suppose so, but I'm not very sure as the number of nQueue (and also nRun) changed too quickly, from zero to hundreds and back to zero.

If I only look at IN2P3-CPPM/SCORE, nQueue=0 (and nRun = 9) at 10:48:54

```
2021-04-12 10:48:54,950 | atlasprodjobbroker | skip site=IN2P3-CPPM/SCORE due to low weight weight=1.7962196219621962 nRun=9 nAct=0 nAss=0 nStart=0 nDef=0 manyAss=1.0 nPilot=2053 totalSizeMB=32 totalNumFiles=1 fileSizeToMoveMB=32 nFilesToMove=1 weightNw=1.8141818181818181 ( closeness=4 nFilesQueued=4 throughputMBps=None Network weight:True ) criteria=-loweigh
```
And then task got preassined at 10:51:40

And  at 10:56:31 suddenly there were nQ >= 300 (and nR = 2k)

```
2021-04-12 10:56:31,721 panda.log.AtlasProdJobBroker: INFO     <jediTaskID=24824923>   skip site=IN2P3-CPPM/SCORE due to low weight weight=16.501087057010785 nRun=3296 nAct=135 nStart=209 nDef=0 nPilot=2061 totalSizeMB=0 totalNumFiles=0 weightNw=1.7717272727272726 ( closeness=5 nFilesQueued=1 throughputMBps=None Network weight:True ) criteria=-loweigh
```

And then at 11:01:53 , mentioned above, nQ was already back to 0 again (and nR = 0)


> Then did the queue filler release all IN2P3-CPPM tasks since IN2P3-CPPM had enough jobs?

Yes, it released all IN2P3-CPPM tasks (actually just the MCORE task 24804088, since now only 1 preassigned task at max is allowed per rtype, and the queue filler did not find any suitable SCORE tasks to preassign).

But the reason to release the tasks was not due to enough jobs in the site but because the task became pending...

```
2021-04-12 11:11:46,249 panda.log.AtlasQueueFillerWatchDog: DEBUG    undo_preassign #ATM #KV jediTaskID=24804088 action=undo_preassign site=IN2P3-CPPM rtype=MCORE un-preassinged since task paused or terminated
```

**Comment by mightqxc** [comment]
Besides, now queue filler runs every 10 minutes. I don't want to run it too frequently but seems it lags to react nQ and nR changes caused by continuous brokerage.

**Comment by tmaeno** [comment]
According to

https://monit-grafana.cern.ch/d/000000696/job-accounting-historical-data?orgId=17&from=now-2d&to=now&var-bin=1h&var-groupby=actualcorecount&var-country=All&var-federation=All&var-resources=All&var-tier=All&var-cloud=All&var-site=All&var-computingsite=IN2P3-CPPM&var-nucleus=All&var-cores=All&var-eventservice=All&var-groups=All&var-inputdatatypes=All&var-inputprojects=All&var-outputproject=All&var-gshare=All&var-resourcesreporting=All&var-processingtype=All&var-jobtype=All&var-prodsourcelabel=All&var-jobstatus=All&var-error_category=All&var-container_name=All&var-es_division_factor=1&var-pledges=CPU

the PQ tends to run more SCORE jobs. I think that it is OK to assign the MCORE task even if it goes to pending
since it can give a chance to run MCORE jobs there. One downside is that the MCORE task might not run even if
there are other empty PQs, if it is trapped with the looping of preassign->pending->release->preassign->...
One possibility is that the queue filler doesn't use tasks if they were recently released due to status=pending.

**Comment by mightqxc** [comment]
@tmaeno In order to filter out tasks which recently got pending, I tried to add the following constraint in the query of tasks to preassign:

```
"AND NOT EXISTS ( "
                                    "SELECT * FROM {jedi_schema}.Tasks_StatusLog sl "
                                    "WHERE sl.jediTaskID=t.jediTaskID "
                                        "AND sl.status='pending' "
                                        "AND sl.modificationTime>=CURRENT_DATE-0.25 "
                                    ") "
```

But this drags down the watchdog significantly: now one watchdog cycle takes 10 minutes (rather than < 1 min. before)
Not sure if there is a way to query Tasks_StatusLog more efficiently.

Another method I figured out is to let queue filler record the taskids which were recently released from preassignment due to status=pending in the cache. But the challenging part is when feeding these "blacklisted" taskids into the sql query of tasks to preassign, it requires a long sql IN-list (`AND t.jediTaskID NOT IN (id1, id2, id3, ...)`) , which looks lame.


Do you have some suggestions? Thanks.

**Comment by tmaeno** [comment]
> it requires a long sql IN-list (AND t.jediTaskID NOT IN (id1, id2, id3, ...)) , which looks lame.

Is there any issue if you get tasks from the database first and skip relevant tasks in the queue filler
rather than putting them into the SQL query?

**Comment by mightqxc** [comment]
Thanks for inspiration. It is implemented and can prevent released tasks from getting preassigned again.

Do you think I can merge this and deploy to all JEDI node?

**Comment by tmaeno** [comment]
Yes.

**Pull request merged**
