### PR TITLE
queue filler watchdog: first commit ; msgprocessor: add processing workflow

### PR DESCRIPTION
**Pull request by mightqxc**

### CODE REVIEW

**Comment by mightqxc** [comment]
@tmaeno Please let me know if it makes sense. Thanks.

**Comment by tmaeno** [comment]
A couple of comments.

* You loop over gshares when looking for available sites. This means that when a gshare doesn't have enough tasks most tasks would be randomly preassigned since most of PQs don't have enough jobs. It is OK if PQs have enough jobs from other gshares. Better to use total nQueue and nRunning instead.

* nQueue should contain only starting and activated. P1 was not happy although there were many assigned since they didn't come to activated quickly enough.

* You would have to increase priorities of preassigned tasks to let them generate jobs immediately since those tasks might be behind other tasks that don't have input data at problematic PQs.

* The site and prio parameters should be reset once the PQs have enough jobs.

**Comment by mightqxc** [comment]
@tmaeno Thanks. I fixed it for the first three points you mentioned.


> The site and prio parameters should be reset once the PQs have enough jobs.

How to implement the "reset"? I mean, where to store the old "site" and "currentPriority" of the tasks?

**Comment by mightqxc** [comment]
I don't know. I'm not sure if this function deserves a new column.

Or in another way, is it ok to store taskid of preassigned tasks in cache table? Then the watchdog knows of which tasks it can undo the change on site and currentpriority.

**Comment by fbarreir** [comment]
I think the main question is if this going to be done on thousands of tasks, or only exceptionally?

If it's going to be done on few tasks, I think it's better to go for cache table (e.g. mainKey=queue_filler, subKey=task_id).

If it's going to be done for a lot of tasks:
- probably jedi_tasks table is better. The main precaution I would point out is that once the column is added, we cannot remove it.
- alternatively, what do you think of extending the tasks_statuslog table? There you could track multiple changes/reassignments. Just be aware that this table gets cleaned on a 3 months sliding window.

**Comment by fbarreir** [comment]
Hi again,
For the cache table option I realized this morning that jeditaskid (number) and the subkey (varchar) are different types. You can make a string out of a number, but it's probably not ideal for the index if it grows a lot. We should then either go for the other options or create a new table.
Regards,
Fernando

**Comment by mightqxc** [comment]
Hi,

To use cache table, I will set mainKey=watchdog_name, subKey=queue , and put all other stuff (tasks, say subset of attributes in json/pickle format) in data, and will guard the cache with lock (with process lock table). The watchdog can query busy PQs and get the preassigned tasks from cache, and reset them.

I think this is going to work as long as the update frequency per site is not too high (e.g. per hour); the quantity of tasks does not matter much (when they all fit in cache data)

**Comment by mightqxc** [comment]
I'm trying dry-run on jedi-00.  The result looks like:

```
2021-03-16 14:50:31,633 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-16/14:50:31.633925> start
2021-03-16 14:50:31,943 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-16/14:50:31.634210> [dry run] rtype=MCORE         3 tasks would be preassigned to GRIF-LPNHE 
2021-03-16 14:50:32,008 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-16/14:50:31.634210> [dry run] rtype=SCORE        52 tasks would be preassigned to GRIF-LPNHE 
2021-03-16 14:50:32,041 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-16/14:50:31.634210> [dry run] rtype=SCORE_HIMEM   3 tasks would be preassigned to GRIF-LPNHE 
2021-03-16 14:50:32,141 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-16/14:50:31.634210> [dry run] rtype=SCORE         6 tasks would be preassigned to ANALY_LRZ_VP 
2021-03-16 14:50:32,209 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-16/14:50:31.634210> [dry run] rtype=MCORE        36 tasks would be preassigned to IN2P3-LAPP-TEST 
2021-03-16 14:50:32,284 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-16/14:50:31.634210> [dry run] rtype=SCORE        60 tasks would be preassigned to IN2P3-LAPP-TEST 
2021-03-16 14:50:32,322 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-16/14:50:31.634210> [dry run] rtype=SCORE_HIMEM   3 tasks would be preassigned to IN2P3-LAPP-TEST 
2021-03-16 14:50:32,429 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-16/14:50:31.634210> [dry run] rtype=SCORE         3 tasks would be preassigned to INFN-COSENZA-RECAS 
...
2021-03-16 14:51:00,074 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-16/14:50:31.634210> [dry run] rtype=MCORE       166 tasks would be preassigned to CERN-BACKFILL 
2021-03-16 14:51:00,225 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-16/14:50:31.634210> [dry run] rtype=SCORE       470 tasks would be preassigned to CERN-BACKFILL 
2021-03-16 14:51:00,269 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-16/14:50:31.634210> [dry run] rtype=SCORE_HIMEM  20 tasks would be preassigned to CERN-BACKFILL 
2021-03-16 14:51:00,314 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-16/14:50:31.634210> [dry run] rtype=MCORE       166 tasks would be preassigned to CERN-HPC 
2021-03-16 14:51:00,431 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-16/14:50:31.634210> [dry run] rtype=SCORE       470 tasks would be preassigned to CERN-HPC 
2021-03-16 14:51:00,473 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-16/14:50:31.634210> [dry run] rtype=SCORE_HIMEM  20 tasks would be preassigned to CERN-HPC 
2021-03-16 14:51:00,645 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-16/14:50:31.633925> done
```

There were 29305 tasks to be preassigned in total. Too many I think.

Is my criterion of "empty site" , as below, too low?
`if nQueue < max(20, nRunning*2)*0.25`

**Comment by mightqxc** [comment]
@tmaeno 

There were ~30k tasks to be preassigned in total, maybe too many.
Also, some tasks are pre-assigned to some testing queues like SWT2_PAUL_TEST , or some minor queues. Not sure if it makes sense.


 My criterion of "empty site" is now:
`if nQueue < max(20, nRunning*2)*0.25`

Do you have some ideas?

**Comment by tmaeno** [comment]
Actually, the selection criteria are too loose. For example, I see INFN-COSENZA-RECAS/CERN-HPC/SWT2_PAUL_TEST are not online. You can ignore brokeroff/test/offline PQs. Also, why do you assign ~700 tasks at CERN-HPC, for example, although only 56 successful jobs were there for the last 3 days?

SQL> select count(*) from atlas_panda.jobsarchived4 where computingsite='CERN-HPC' and jobstatus='finished';

       COUNT(*)
---------------
	     56

**Comment by mightqxc** [comment]
@tmaeno Thanks. And how about the result below now?
Only a few hundred tasks preassigned (there is a limit of max 3 tasks per site+rtype)

```
2021-03-19 06:44:24,334 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-19/06:44:24.334707> start
2021-03-19 06:44:24,473 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-19/06:44:24.334865> [dry run] rtype=MCORE         3 tasks would be preassigned to UNI-FREIBURG 
2021-03-19 06:44:24,555 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-19/06:44:24.334865> [dry run] rtype=SCORE         3 tasks would be preassigned to UNI-FREIBURG 
2021-03-19 06:44:24,597 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-19/06:44:24.334865> [dry run] rtype=SCORE_HIMEM   3 tasks would be preassigned to UNI-FREIBURG 
2021-03-19 06:44:24,709 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-19/06:44:24.334865> [dry run] rtype=SCORE         3 tasks would be preassigned to ANALY_MWT2_VP 
2021-03-19 06:44:24,784 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-19/06:44:24.334865> [dry run] rtype=MCORE         3 tasks would be preassigned to ANALY_BNL_LAKE 
2021-03-19 06:44:24,862 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-19/06:44:24.334865> [dry run] rtype=SCORE         3 tasks would be preassigned to ANALY_BNL_LAKE 
2021-03-19 06:44:24,902 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-19/06:44:24.334865> [dry run] rtype=SCORE_HIMEM   3 tasks would be preassigned to ANALY_BNL_LAKE 
2021-03-19 06:44:24,946 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-19/06:44:24.334865> [dry run] rtype=MCORE         3 tasks would be preassigned to ANALY_ARNES_DIRECT 
2021-03-19 06:44:25,041 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-19/06:44:24.334865> [dry run] rtype=SCORE         3 tasks would be preassigned to ANALY_ARNES_DIRECT 
2021-03-19 06:44:25,088 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-19/06:44:24.334865> [dry run] rtype=SCORE_HIMEM   3 tasks would be preassigned to ANALY_ARNES_DIRECT 
2021-03-19 06:44:25,125 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-19/06:44:24.334865> [dry run] rtype=MCORE         3 tasks would be preassigned to GRIF-IRFU 
2021-03-19 06:44:25,211 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-19/06:44:24.334865> [dry run] rtype=SCORE         3 tasks would be preassigned to GRIF-IRFU 
2021-03-19 06:44:25,250 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-19/06:44:24.334865> [dry run] rtype=SCORE_HIMEM   2 tasks would be preassigned to GRIF-IRFU 
2021-03-19 06:44:25,287 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-19/06:44:24.334865> [dry run] rtype=MCORE         1 tasks would be preassigned to UKI-NORTHGRID-LIV-HEP 
2021-03-19 06:44:25,362 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-19/06:44:24.334865> [dry run] rtype=SCORE         3 tasks would be preassigned to UKI-NORTHGRID-LIV-HEP 
2021-03-19 06:44:25,432 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-19/06:44:24.334865> [dry run] rtype=MCORE         1 tasks would be preassigned to TR-10-ULAKBIM_UCORE 
2021-03-19 06:44:25,503 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-19/06:44:24.334865> [dry run] rtype=SCORE         3 tasks would be preassigned to TR-10-ULAKBIM_UCORE 
2021-03-19 06:44:25,568 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-19/06:44:24.334865> [dry run] rtype=MCORE         3 tasks would be preassigned to praguelcg2_Barbora_MCORE 
2021-03-19 06:44:25,633 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-19/06:44:24.334865> [dry run] rtype=SCORE         3 tasks would be preassigned to praguelcg2_Barbora_MCORE 
2021-03-19 06:44:25,668 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-19/06:44:24.334865> [dry run] rtype=SCORE_HIMEM   3 tasks would be preassigned to praguelcg2_Barbora_MCORE 
2021-03-19 06:44:25,712 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-19/06:44:24.334865> [dry run] rtype=MCORE         3 tasks would be preassigned to TOKYO 
2021-03-19 06:44:25,802 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-19/06:44:24.334865> [dry run] rtype=SCORE         3 tasks would be preassigned to TOKYO 
2021-03-19 06:44:25,843 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-19/06:44:24.334865> [dry run] rtype=SCORE_HIMEM   3 tasks would be preassigned to TOKYO 
2021-03-19 06:44:25,893 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-19/06:44:24.334865> [dry run] rtype=MCORE         3 tasks would be preassigned to MWT2_VHIMEM_UCORE 
2021-03-19 06:44:26,005 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-19/06:44:24.334865> [dry run] rtype=SCORE         3 tasks would be preassigned to MWT2_VHIMEM_UCORE 
2021-03-19 06:44:26,053 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-19/06:44:24.334865> [dry run] rtype=SCORE_HIMEM   3 tasks would be preassigned to MWT2_VHIMEM_UCORE 
2021-03-19 06:44:26,117 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-19/06:44:24.334865> [dry run] rtype=MCORE         3 tasks would be preassigned to MWT2 
2021-03-19 06:44:26,212 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-19/06:44:24.334865> [dry run] rtype=SCORE         3 tasks would be preassigned to MWT2 
2021-03-19 06:44:26,263 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-19/06:44:24.334865> [dry run] rtype=SCORE_HIMEM   3 tasks would be preassigned to MWT2 
2021-03-19 06:44:26,377 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-19/06:44:24.334865> [dry run] rtype=SCORE         3 tasks would be preassigned to IN2P3-LPC 
2021-03-19 06:44:26,416 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-19/06:44:24.334865> [dry run] rtype=SCORE_HIMEM   2 tasks would be preassigned to IN2P3-LPC 
2021-03-19 06:44:26,459 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-19/06:44:24.334865> [dry run] rtype=MCORE         3 tasks would be preassigned to NET2 
2021-03-19 06:44:26,543 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-19/06:44:24.334865> [dry run] rtype=SCORE         3 tasks would be preassigned to NET2 
2021-03-19 06:44:26,591 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-19/06:44:24.334865> [dry run] rtype=SCORE_HIMEM   3 tasks would be preassigned to NET2 
2021-03-19 06:44:26,639 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-19/06:44:24.334865> [dry run] rtype=MCORE         3 tasks would be preassigned to DE-TARDIS 
2021-03-19 06:44:26,740 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-19/06:44:24.334865> [dry run] rtype=SCORE         3 tasks would be preassigned to DE-TARDIS 
2021-03-19 06:44:26,789 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-19/06:44:24.334865> [dry run] rtype=SCORE_HIMEM   3 tasks would be preassigned to DE-TARDIS 
2021-03-19 06:44:26,828 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-19/06:44:24.334865> [dry run] rtype=MCORE         3 tasks would be preassigned to PNPI_PROD 
2021-03-19 06:44:26,909 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-19/06:44:24.334865> [dry run] rtype=SCORE         3 tasks would be preassigned to PNPI_PROD 
2021-03-19 06:44:26,958 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-19/06:44:24.334865> [dry run] rtype=SCORE_HIMEM   3 tasks would be preassigned to PNPI_PROD 
2021-03-19 06:44:26,996 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-19/06:44:24.334865> [dry run] rtype=MCORE         3 tasks would be preassigned to DESY-ZN 
2021-03-19 06:44:27,069 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-19/06:44:24.334865> [dry run] rtype=SCORE         3 tasks would be preassigned to DESY-ZN 
2021-03-19 06:44:27,107 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-19/06:44:24.334865> [dry run] rtype=SCORE_HIMEM   1 tasks would be preassigned to DESY-ZN 
2021-03-19 06:44:27,139 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-19/06:44:24.334865> [dry run] rtype=MCORE         3 tasks would be preassigned to UTA_SWT2_UCORE 
2021-03-19 06:44:27,203 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-19/06:44:24.334865> [dry run] rtype=SCORE         3 tasks would be preassigned to UTA_SWT2_UCORE 
2021-03-19 06:44:27,271 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-19/06:44:24.334865> [dry run] rtype=MCORE         1 tasks would be preassigned to ANALY_LRZ_VP 
2021-03-19 06:44:27,345 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-19/06:44:24.334865> [dry run] rtype=SCORE         3 tasks would be preassigned to ANALY_LRZ_VP 
2021-03-19 06:44:27,496 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-19/06:44:24.334865> [dry run] rtype=SCORE         3 tasks would be preassigned to UKI-SOUTHGRID-OX-HEP 
2021-03-19 06:44:27,532 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-19/06:44:24.334865> [dry run] rtype=SCORE_HIMEM   2 tasks would be preassigned to UKI-SOUTHGRID-OX-HEP 
2021-03-19 06:44:27,573 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-19/06:44:24.334865> [dry run] rtype=MCORE         1 tasks would be preassigned to IN2P3-LPSC 
2021-03-19 06:44:27,657 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-19/06:44:24.334865> [dry run] rtype=SCORE         3 tasks would be preassigned to IN2P3-LPSC 
2021-03-19 06:44:27,693 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-19/06:44:24.334865> [dry run] rtype=SCORE_HIMEM   3 tasks would be preassigned to IN2P3-LPSC 
2021-03-19 06:44:27,733 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-19/06:44:24.334865> [dry run] rtype=MCORE         3 tasks would be preassigned to UKI-LT2-QMUL 
2021-03-19 06:44:27,817 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-19/06:44:24.334865> [dry run] rtype=SCORE         3 tasks would be preassigned to UKI-LT2-QMUL 
2021-03-19 06:44:27,860 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-19/06:44:24.334865> [dry run] rtype=SCORE_HIMEM   3 tasks would be preassigned to UKI-LT2-QMUL 
2021-03-19 06:44:27,895 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-19/06:44:24.334865> [dry run] rtype=MCORE         3 tasks would be preassigned to UKI-LT2-IC-HEP_SL7_UCORE 
2021-03-19 06:44:27,962 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-19/06:44:24.334865> [dry run] rtype=SCORE         3 tasks would be preassigned to UKI-LT2-IC-HEP_SL7_UCORE 
2021-03-19 06:44:27,997 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-19/06:44:24.334865> [dry run] rtype=SCORE_HIMEM   3 tasks would be preassigned to UKI-LT2-IC-HEP_SL7_UCORE 
2021-03-19 06:44:28,043 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-19/06:44:24.334865> [dry run] rtype=MCORE         3 tasks would be preassigned to UKI-NORTHGRID-MAN-HEP 
2021-03-19 06:44:28,090 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-19/06:44:24.334865> [dry run] rtype=MCORE_HIMEM   1 tasks would be preassigned to UKI-NORTHGRID-MAN-HEP 
2021-03-19 06:44:28,133 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-19/06:44:24.334865> [dry run] rtype=SCORE         3 tasks would be preassigned to UKI-NORTHGRID-MAN-HEP 
2021-03-19 06:44:28,173 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-19/06:44:24.334865> [dry run] rtype=SCORE_HIMEM   3 tasks would be preassigned to UKI-NORTHGRID-MAN-HEP 
2021-03-19 06:44:28,210 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-19/06:44:24.334865> [dry run] rtype=MCORE         1 tasks would be preassigned to GRIF-LAL 
2021-03-19 06:44:28,288 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-19/06:44:24.334865> [dry run] rtype=SCORE         3 tasks would be preassigned to GRIF-LAL 
2021-03-19 06:44:28,327 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-19/06:44:24.334865> [dry run] rtype=SCORE_HIMEM   3 tasks would be preassigned to GRIF-LAL 
2021-03-19 06:44:28,376 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-19/06:44:24.334865> [dry run] rtype=MCORE         3 tasks would be preassigned to AGLT2 
2021-03-19 06:44:28,469 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-19/06:44:24.334865> [dry run] rtype=SCORE         3 tasks would be preassigned to AGLT2 
2021-03-19 06:44:28,515 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-19/06:44:24.334865> [dry run] rtype=SCORE_HIMEM   3 tasks would be preassigned to AGLT2 
2021-03-19 06:44:28,551 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-19/06:44:24.334865> [dry run] rtype=MCORE         3 tasks would be preassigned to HEPHY-UIBK 
2021-03-19 06:44:28,621 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-19/06:44:24.334865> [dry run] rtype=SCORE         3 tasks would be preassigned to HEPHY-UIBK 
2021-03-19 06:44:28,656 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-19/06:44:24.334865> [dry run] rtype=SCORE_HIMEM   2 tasks would be preassigned to HEPHY-UIBK 
2021-03-19 06:44:28,705 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-19/06:44:24.334865> [dry run] rtype=MCORE         3 tasks would be preassigned to SiGNET 
2021-03-19 06:44:28,797 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-19/06:44:24.334865> [dry run] rtype=SCORE         3 tasks would be preassigned to SiGNET 
2021-03-19 06:44:28,846 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-19/06:44:24.334865> [dry run] rtype=SCORE_HIMEM   3 tasks would be preassigned to SiGNET 
2021-03-19 06:44:28,902 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-19/06:44:24.334865> [dry run] rtype=MCORE         1 tasks would be preassigned to UKI-LT2-RHUL 
2021-03-19 06:44:28,989 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-19/06:44:24.334865> [dry run] rtype=SCORE         3 tasks would be preassigned to UKI-LT2-RHUL 
2021-03-19 06:44:29,027 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-19/06:44:24.334865> [dry run] rtype=SCORE_HIMEM   3 tasks would be preassigned to UKI-LT2-RHUL 
2021-03-19 06:44:29,069 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-19/06:44:24.334865> [dry run] rtype=MCORE         1 tasks would be preassigned to GRIF-LPNHE 
2021-03-19 06:44:29,144 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-19/06:44:24.334865> [dry run] rtype=SCORE         3 tasks would be preassigned to GRIF-LPNHE 
2021-03-19 06:44:29,183 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-19/06:44:24.334865> [dry run] rtype=SCORE_HIMEM   3 tasks would be preassigned to GRIF-LPNHE 
2021-03-19 06:44:29,315 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-19/06:44:24.334865> [dry run] rtype=SCORE         3 tasks would be preassigned to INFN-FRASCATI 
2021-03-19 06:44:29,352 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-19/06:44:24.334865> [dry run] rtype=SCORE_HIMEM   3 tasks would be preassigned to INFN-FRASCATI 
2021-03-19 06:44:29,399 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-19/06:44:24.334865> [dry run] rtype=MCORE         3 tasks would be preassigned to IN2P3-LAPP 
2021-03-19 06:44:29,479 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-19/06:44:24.334865> [dry run] rtype=SCORE         3 tasks would be preassigned to IN2P3-LAPP 
2021-03-19 06:44:29,518 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-19/06:44:24.334865> [dry run] rtype=SCORE_HIMEM   3 tasks would be preassigned to IN2P3-LAPP 
2021-03-19 06:44:29,576 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-19/06:44:24.334865> [dry run] rtype=MCORE         3 tasks would be preassigned to BNL_VHIMEM 
2021-03-19 06:44:29,629 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-19/06:44:24.334865> [dry run] rtype=MCORE_HIMEM   1 tasks would be preassigned to BNL_VHIMEM 
2021-03-19 06:44:29,701 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-19/06:44:24.334865> [dry run] rtype=SCORE         3 tasks would be preassigned to BNL_VHIMEM 
2021-03-19 06:44:29,759 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-19/06:44:24.334865> [dry run] rtype=SCORE_HIMEM   3 tasks would be preassigned to BNL_VHIMEM 
2021-03-19 06:44:29,760 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-19/06:44:24.334707> done
```

**Comment by tmaeno** [comment]
Looks better now, but you should remove ANALY PQs and take capability/minrss/maxrss/corecount into account
when preassigning tasks. e.g.,

2021-03-19 06:44:29,701 panda.log.AtlasQueueFillerWatchDog: DEBUG    <2021-03-19/06:44:24.334865> [dry run] rtype=SCORE         3 tasks would be preassigned to BNL_VHIMEM 

I guess that those tasks cannot run there since the PQ has minrss=32001

**Comment by tmaeno** [comment]
I've added a couple of changes to the master branch and updated production JEDI nodes except for your node. Can you merge those changes on that node?

**Comment by mightqxc** [comment]
ok done

**Comment by mightqxc** [comment]
@tmaeno I think now it is OK to merge this one (only dry-run), if you agree with the code.

Can we try to enable the real run this week? I will inform DPA and open another pull request for it.

**Comment by tmaeno** [comment]
OK, thanks. Go ahead.

**Pull request merged**
