### PR TITLE
Remove getRelCacheForJumbo_JEDI

### PR DESCRIPTION
**Pull request by fbarreir**

### CODE REVIEW

**Comment by fbarreir** [comment]
@tmaeno we mentioned this in a meeting last week, but can you please confirm that removing getRelCacheForJumbo_JEDI is OK?

**Comment by tmaeno** [comment]
Hi Fernando,

I think it is OK to remove
https://github.com/PanDAWMS/panda-jedi/blob/55d82c7d9f4a2b0aed2572b1caa02468beaeef72/pandajedi/jedidog/JumboWatchDog.py#L131-L190

**Comment by fbarreir** [comment]
Thanks. That change also obsoletes `getTaskToEnableJumbo_JEDI`: https://github.com/PanDAWMS/panda-jedi/pull/99/commits/97f525f448501720859cfccffee4dad7841a027d
OK? 

I will install the branch on one JEDI machine, before merging probably tomorrow morning.

**Comment by tmaeno** [comment]
OK.

**Pull request merged**
